train/mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path
from myapp import views

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='index'),
    path('products', views.products, name='product'),
    path('about', views.about, name='about'),
    
#    book/1
    path('book/<int:book_id>/', views.detail, name='detail'),
    path('add/', views.add_book, name='add_book'),
    path('update/<int:id>/', views.update, name='update'),
    path('delete/<int:id>/', views.delete, name='delete'),

]

train/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from myapp import views
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

train/mysite/myapp/models.py
from django.db import models

# Create your models here.

class Book(models.Model):

    def __str__(self):
        return self.name

    name = models.CharField(max_length=100)
    desc = models.CharField(max_length=300)
    price = models.IntegerField()
    book_image =models.ImageField(default='default.jpg', upload_to='book_images/')
    author = models.CharField(max_length=100, default='anonymous')

train/mysite/myapp/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
    class Meta:
        model = Book
        #fields = ['name', 'desc', 'book_image', 'price']
        fields = '__all__'

train/mysite/myapp/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Book
from .forms import BookForm


# Create your views here.

def index(request):
    return HttpResponse('<b>Hello!!!!</b>')

def products(request):
    book_list = Book.objects.all()
    context = {
        'book_list': book_list
    }
#    return HttpResponse(book_list)
    return render(request, 'myapp/products.html', context)

def detail(request, book_id):
    book_item = Book.objects.get(id = book_id)
    return render(request, 'myapp/book.html', {'book_item': book_item})
   # return HttpResponse("This is a book number %s" % book_id)

def about(request):
    return HttpResponse("about us!!")

def add_book(request):
    if request.method == 'POST':
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        price = request.POST.get('price',)
        book_image = request.FILES['book_image']

        book = Book(name=name, desc=desc, price=price, book_image=book_image)
        book.save()

    return render(request, 'myapp/add_book.html')


def update(request, id):
    book = Book.objects.get(id=id)
    form = BookForm(request.POST or None, request.FILES, instance=book)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, 'myapp/edit.html', {'form': form, 'book': book})

def delete(request,id):
    if request.method == 'POST':
        book = Book.objects.get(id=id)
        book.delete()
        return redirect('/')
    return render(request, 'myapp/delete.html')

train/mysite/myapp/templates/myapp/add_book.html
{% extends 'myapp/base.html' %}

{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
Book title<br>
<input type="text" name="name" id="name" placeholder="some book name"><br>
Descrioption<br>
<input type="text" name="desc" id="desc" placeholder="some book description"><br>
Price<br>
<input type="text" name="price" id="price" placeholder="some book name"><br>
Image<br>
<input type="file" name="book_image" id="book_image" placeholder="some book name"><br>
<br>
<input type="Submit">
</form>

{% endblock %}

train/mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
        <link rel="stylesheet" href="{% static 'myapp/style.css' %}" />
        
        <title>Bookstore</title>

    </head>

    <body>
        <!-- Image and text -->
        <nav class="navbar navbar-dark bg-dark">
            <a class="navbar-brand" href="#">
            Bookstore
            </a>
        </nav>

        {% block body %}
            
        {% endblock %}


    </body>
</html>

train/mysite/myapp/templates/myapp/book.html
{% extends 'myapp/base.html' %}

{% block body %}

<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{book_item.book_image.url}}" width="300">
        </div>

        <div class="col-md-6">
            <h1>{{book_item.name}}</h1>
            <p>Description: {{book_item.desc}}</p>
            <p>Price: {{book_item.price}}</p>

            <a class="btn btn-warning" href="{% url 'myapp:update' book_item.id %}">EDIT</a>
            <a class="btn btn-danger" href="{% url 'myapp:delete' book_item.id %}">DELETE</a>

        </div>
    </div>
</div>


{% endblock %}

train/mysite/myapp/templates/myapp/delete.html
<form method="POST">
    {% csrf_token %}
    Are you sure you want to delete this book? 
    <input type="submit">
</form>

train/mysite/myapp/templates/myapp/edit.html
<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" id="">
</form>

train/mysite/myapp/templates/myapp/products.html
{% extends 'myapp/base.html' %}

{% block body %}
<h1>Product list</h1>
<div class="container">
    <div class="row">
        <div class="col-md-3">

            {% for book in book_list %}
            <div class="card">
                <img class="card-img-top" src="{{book.book_image.url}}">
                <div class="card-body">
                    <h3 class="card-title"><a href="{% url 'myapp:detail' book.id %}">{{book.name}}</a></h3>
                    <p class="card-text">{{book.desc}}</p>
                    <p class="card-text">{{book.price}}</p> 
                </div>
            </div>
            {% endfor %}

        </div>
    </div>
</div>

{% endblock %}